[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/kubernetes"
  version = "1.9.3"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  branch = "master"
  # version = "=v0.0.5"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v9.10.0"
